#
#   This is the config file for the PBFetcher Python script
#   All the settings and what they do is explained in the comments next to them
#   Credits: https://github.com/skill3472/
#

# This is the time format you want to have displayed under each update. Leave empty, for none.
# Refer to the Python3 datetime documentation for all possible date params
time: "%H:%M:%S GMT+2:00 Time"

# The file you want the program to update
out_file: "out.md"

# The line in the file, that you want to be updated with the PB and
# the line in the file, that you want to have the timestamp on.
# Set to -1 to disable the timestamp 
# Number of line is counted from 0. So the first line is 0, second is 1, etc.
out_line: 1
timestamp_line: 2